name: Docker image

# trigger
on:
  push:
    branches: ["stage"]

env:
  REGISTRY: cachac
  IMAGE_NAME: kubelabs_publicapi
  OPS_BRANCH: main
  OPS_REPO: cachac/antonio-ops
  

jobs: 
  build: 
    runs-on: ubuntu-latest

    outputs:
      RELEASE_VERSION: ${{ steps.tagVersion.outputs.RELEASE_VERSION }}

    steps: 
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get TAG version
        run: echo "RELEASE_VERSION=$(git tag  --sort=-creatordate | head -1)" >> $GITHUB_ENV

      - name: Show new tag
        id: tagVersion
        run: |
          echo ${{ env.RELEASE_VERSION }}
          echo "::set-output name=RELEASE_VERSION::${{ env.RELEASE_VERSION }}"
      
      
      - name: Login to Dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push
        uses: docker/build-push-action@v3
        with: 
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.RELEASE_VERSION }}
          build-args: |
            APP_ENV=${{ secrets.APP_ENV }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    env: 
      VERSION: ${{ needs.build.outputs.RELEASE_VERSION }}
    
    steps:
      - name: Checkout OPS code
        uses: actions/checkout@v3
        with:
          repository: ${{ env.OPS_REPO }}
          ssh-key:; ${{ secrets.OPS_TOKEN }}

      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v2
        with:
          kustomize-version: "3.6.1"

      - name: update Kubernetes resource
        run: |
          cd public-api/overlays/stage
          kustomize edit set image KUSTOMIZE-DEFINED=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}

          # OPCIONAL
          kustomize build . > app.yaml
          cat app.yaml

      - name: Commit files
        run: |
          git add .
          git commit -am "New image version. Branch staging. tag: ${{ env.VERSION }}"
          git push --force origin ${{ env.OPS_BRANCH }}

      

      
        
